services:
  app:
    ports:
      - "${APP_PORT}:${APP_PORT}"
    build:
      dockerfile: Dockerfile.prod
    env_file: 
      - .env.production
    secrets:
      - DB_USER
      - DB_PASSWORD
      - DB_NAME

secrets:
  DB_PASSWORD:
    file: ./secrets/db_password.txt
  DB_NAME:
    file: ./secrets/db_name.txt
  IMAGES_PASSWORD:
    file: ./secrets/images_password.txt
  IMAGES_USER:
    file: ./secrets/images_username.txt
  REDIS_USER:
    file: ./secrets/redis_username.txt
  REDIS_PASSWORD:
    file: ./secrets/redis_password.txt