services:
  app:
    ports:
      - "${APP_PORT}:${APP_PORT}"
    build:
      dockerfile: Dockerfile.prod
    env_file: 
      - .env.production
    secrets:
      - DB_USER
      - DB_PASSWORD
      - DB_NAME

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    secrets:
      - DB_PASSWORD
      - DB_NAME
      - DB_USER
    environment:
      MYSQL_ROOT_PASSWORD: /secrets/DB_PASSWORD
      DB_USER: /secrets/DB_USER
      MYSQL_DATABASE: /secrets/DB_NAME
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "${REDIS_PORT}:6379"

secrets:
  DB_PASSWORD:
    file: ./secrets/db_password.txt
  DB_NAME:
    file: ./secrets/db_name.txt
  IMAGES_PASSWORD:
    file: ./secrets/images_password.txt
  IMAGES_USER:
    file: ./secrets/images_username.txt
  REDIS_USER:
    file: ./secrets/redis_username.txt
  REDIS_PASSWORD:
    file: ./secrets/redis_password.txt