services:
  db:
    container_name: mysql_db
    image: mysql:8
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  redis:
    container_name: redis_cache
    image: redis:7

  images:
    container_name: images